#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 26 17:15:18 2018

@author: tensorflow-cuda
"""

from custom_plate import test as t

text = '!@#$%T%^*N()_+38`~<>?:A"{}3|4\5/6.,;[]'
t.catch_rectify_plate_characters(text)